apiVersion: v1
kind: Namespace
metadata:
  name: vote-ns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: db-service
  name: db
  namespace: vote-ns
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: demo-voting-app
    name: postgres-pod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: redis-service
  name: redis
  namespace: vote-ns
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: demo-voting-app
    name: redis-pod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: result-service
  name: result-service
  namespace: vote-ns
spec:
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80
  selector:
    app: demo-voting-app
    name: result-app-pod
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: voting-service
  name: voting-service
  namespace: vote-ns
spec:
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
  selector:
    app: demo-voting-app
    name: voting-app-pod
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/hostpath-provisioner/vote-ns/postgres-pv-claim
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: postgres-dp
  namespace: vote-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: postgres-pod
      name: postgres-pod
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:10-alpine
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: redis-dp
  namespace: vote-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: redis-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: redis-pod
      name: redis-pod
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: result-app-dp
  namespace: vote-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: result-app-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: result-app-pod
      name: result-app-pod
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result-app
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: voting-app-dp
  namespace: vote-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-app-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: voting-app-pod
      name: voting-app-pod
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:v1
        name: voting-app
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: worker-app-dp
  namespace: vote-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: worker-app-pod
      name: worker-app-pod
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker-app
