apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    hostPathProvisionerIdentity: 3ede69c5-a726-424e-b167-9c9c775e84f3
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  creationTimestamp: "2022-11-07T15:38:03Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-f0b82cb1-20be-4011-8ea3-442e66c93b2c
  resourceVersion: "698"
  uid: f8520590-9599-4fc6-ae39-3ed423a59c74
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-pv-claim
    namespace: vote-ns
    resourceVersion: "683"
    uid: f0b82cb1-20be-4011-8ea3-442e66c93b2c
  hostPath:
    path: /tmp/hostpath-provisioner/vote-ns/postgres-pv-claim
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound



